name: Publish Package to npmjs
on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      id-token: write  # Required for OIDC
      contents: write
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - run: yarn npm publish --access public

